### ISSUE TITLE
Запит функції? / Feature Request?

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [vadimdemedes/ink-ui#6]
українська / Ukrainian

Чи може/чи буде "ink-ui" у своєму поточному стані підтримувати NodeGUI?

 https://github.com/nodegui/nodegui

 Якщо ні, які кроки будуть потрібні для досягнення цього?

англійська / English

Could/Would "ink-ui" in its current state support NodeGUI?

https://github.com/nodegui/nodegui

If it doesn't, what steps would be needed in order to achieve this?

**Comment by vadimdemedes** [comment]
Duplicate of https://github.com/vadimdemedes/pastel/issues/57.
